server {
    listen 80;
    server_name expertisoracademy.in www.expertisoracademy.in;
    client_max_body_size 50M;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip Compression
    gzip_static on;
    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    # Caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Don't cache HTML to ensure updates are seen
    location ~* \.html$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location / {
        try_files $uri /index.html;
    }

    # Proxy API requests to the backend service
    location /api {
        proxy_pass http://backend:80/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Handle /auth/success in the frontend (React)
    location /auth/success {
        try_files $uri /index.html;
    }

    # Proxy SSO requests
    location /auth {
        proxy_pass http://sso:5999/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
