const pages ={
    marketing_Affiliate:{
        title:"Affiliate Marketing",
        description:"",
        keywords:"",
        hero_img:"",
        hero_title:"Ready to Build a High Paying IT Career?",
        hero_description:"Learn Directly from Tamil Nadu's Top Tech Creators & Mentors!",
        hero_button:"",
        coupon_code:{
            title:"",
            description:"",
            coupon_code:"",
            expiry_date:"30-07-2025 11:59 PM",
        },
        how_it_works:{
            title:"",
            description:"",
            card_1:{
                title:"",
                description:"",
            },
            card_2:{
                title:"",
                description:"",
            },
            card_3:{
                title:"",
                description:"",
            },
            card_4:{
                title:"",
                description:"",
            }
        },
        mentors:{
            title:"",
            description:"",
            image_path:"",
            ratings:"",
            students_count:"",
            no_of_course:"",
            social_handles:{
                facebook:"",
                twitter:"",
                instagram:"",
                linkedin:"",
            }
        },
        painPoints:{
            title:"",
            description:"",
            tags:[
                "",
                "",
                "",
            ]
        },
        benefits:{
            title:"",
            description:"",
            tags:[
                "",
                "",
                "",
            ]
        }
    },
    civil_3ds_max:{
        title:"3ds max",
        description:"",
        keywords:"",
        hero_img:"",
        hero_title:"",
        hero_description:"",
        hero_button:"",
        how_it_works:{
            title:"",
            description:"",
            card_1:{
                title:"",
                description:"",
            },
            card_2:{
                title:"",
                description:"",
            },
            card_3:{
                title:"",
                description:"",
            },
            card_4:{
                title:"",
                description:"",
            }
        },
        mentors:{
            title:"",
            description:"",
            ratings:"",
            students_count:"",

        }
    },
    marketing_digital_marketing:{
        title:"Digital Marketing",
        description:"",
        keywords:"",
        hero_img:"",
        hero_title:"",
        hero_description:"",
        hero_button:"",
        how_it_works:{
            title:"",
            description:"",
            card_1:{
                title:"",
                description:"",
            },
            card_2:{
                title:"",
                description:"",
            },
            card_3:{
                title:"",
                description:"",
            },
            card_4:{
                title:"",
                description:"",
            }
        },
        mentors:{
            title:"",
            description:"",
            ratings:"",
            students_count:"",

        }
    },
    tech_python:{
        title:"Affiliate",
        description:"",
        keywords:"",
        hero_img:"",
        hero_title:"",
        hero_description:"",
        hero_button:"",
        how_it_works:{
            title:"",
            description:"",
            card_1:{
                title:"",
                description:"",
            },
            card_2:{
                title:"",
                description:"",
            },
            card_3:{
                title:"",
                description:"",
            },
            card_4:{
                title:"",
                description:"",
            }
        },
        mentors:{
            title:"",
            description:"",
            ratings:"",
            students_count:"",
            no_of_course:"",
            social_handles:{
                facebook:"",
                twitter:"",
                instagram:"",
                linkedin:"",
            }
        }
    }
}